/**
 * Vendor the webappanalyzer rule set (community fork of the open Wappalyzer
 * rules) into data/fingerprints/technologies.json.
 *
 * Only technologies in categories we map (lib/categories.ts) are kept, and
 * only the fields a single homepage fetch can evaluate: headers, cookies,
 * meta, html, scriptSrc, url. Browser-only fields (js, dom, css, xhr) and
 * `implies` are dropped: we only report what we have evidence for.
 *
 *   pnpm sync:fingerprints [--ref main]
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { categoryFromWappalyzer } from "../lib/categories";

const REPO = "enthec/webappanalyzer";
const ref = process.argv.includes("--ref") ? process.argv[process.argv.indexOf("--ref") + 1] : "main";
const base = `https://raw.githubusercontent.com/${REPO}/${ref}/src`;
const FILES = ["_", ..."abcdefghijklmnopqrstuvwxyz"].map((c) => `technologies/${c}.json`);
const KEEP = ["cats", "website", "headers", "cookies", "meta", "html", "scriptSrc", "url", "requires", "requiresCategory", "excludes"] as const;
const MATCHABLE = ["headers", "cookies", "meta", "html", "scriptSrc", "url"];

async function get(file: string): Promise<Record<string, Record<string, unknown>>> {
  const res = await fetch(`${base}/${file}`, { signal: AbortSignal.timeout(60_000) });
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  return res.json();
}

async function main() {
  const all: Record<string, Record<string, unknown>> = {};
  for (const f of FILES) {
    Object.assign(all, await get(f));
    process.stdout.write(".");
  }
  process.stdout.write("\n");

  const out: Record<string, Record<string, unknown>> = {};
  for (const [name, tech] of Object.entries(all)) {
    const cats = (tech.cats as number[] | undefined) ?? [];
    if (!categoryFromWappalyzer(cats)) continue;
    if (!MATCHABLE.some((k) => k in tech)) continue;
    const slim: Record<string, unknown> = {};
    for (const k of KEEP) if (k in tech) slim[k] = tech[k];
    out[name] = slim;
  }

  const dir = path.join(process.cwd(), "data/fingerprints");
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "technologies.json"), JSON.stringify(out));
  await writeFile(
    path.join(dir, "SOURCE.md"),
    `Generated by scripts/sync-fingerprints.ts from https://github.com/${REPO} (ref: ${ref}) on ${new Date().toISOString().slice(0, 10)}.\n` +
      `Rules are GPL-3.0 licensed by their authors. Kept ${Object.keys(out).length} of ${Object.keys(all).length} technologies.\n`,
  );
  console.log(`kept ${Object.keys(out).length} / ${Object.keys(all).length} technologies`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
